### PR TITLE
Update deployOpenShift.sh

### PR DESCRIPTION
**Pull request by dwaiba**
Temp. Fix with openshift_disable_check=package_version in the variables common for all OSEv3 hosts as per this [Solution](https://access.redhat.com/solutions/3376031)

### CODE REVIEW

**Comment by dwaiba** [comment]
Besides Temp. Fix @vincepower pull #50 additions for docker 1.12.6 pinning added openshift_disable_check=package_version for  with openshift_disable_check=package_version in the variables common for all OSEv3 hosts . All Commits as per this [Solution](https://access.redhat.com/solutions/3376031) for [bug 1551862](https://bugzilla.redhat.com/show_bug.cgi?id=1551862) . Rest commits on preps for master and node for GlusterFS Prereqs.  /etc/multipath.conf device entry, restart with extra raw block (disk attachment for GlusterFS)  pending

**Comment by dwaiba** [comment]
Testing and works.. Switching to point to [repo master](https://github.com/Microsoft/openshift-container-platform)

**Comment by mavis1827** [comment]
@dwaiba I did made the below changes to my scripts and still run into the same failure. Any suggestions/workarounds are highly appreciated.

**Comment by dwaiba** [comment]
without logging true

**Comment by mavis1827** [comment]
In deployOpenShift.sh script? It's already set to false in both deployOpenShift.sh and azuredeploy.parameters.json files.

**Comment by mavis1827** [comment]
i'm using Release 3.7 branch for my deployment.

**Comment by dwaiba** [comment]
Thank you @mavis1827, would it be possible to share the master deploy json url ?

**Comment by mavis1827** [comment]
Sure. Attached is the azuredeploy.json file (please rename by removing the .log at the end of the file).
[azuredeploy.json.log](https://github.com/Microsoft/openshift-container-platform/files/1831315/azuredeploy.json.log)

**Comment by dwaiba** [comment]
@mavis1827 you are hitting with  "defaultValue": "https://raw.githubusercontent.com/Microsoft/openshift-container-platform/release-3.7" which is changed as per commit URL https://github.com/Microsoft/openshift-container-platform/pull/53/commits/0cdd1d0692881dde8cfe27be958b0aa62bd53a91 .

This would only work when the pull is merged. For now if you manually change "Microsoft" in the default value to "dwaiba" it will work until the pull is merged.

**Comment by mavis1827** [comment]
@dwaiba thank you! i did made the change to the "defaultValue" line and still encounter the same failure. Attached "OCPOnAzureDeploymetFailed.txt" has the failure messages. Also attaching the scripts and azuredeploy.json for your review. It's not clear why it's kept on checking for latest versions and failing the deployment. Note: this deployment is without gluster. 

[OCPOnAzureDeploymetFailed.txt](https://github.com/Microsoft/openshift-container-platform/files/1834365/OCPOnAzureDeploymetFailed.txt)
[azuredeploy .json.txt](https://github.com/Microsoft/openshift-container-platform/files/1834368/azuredeploy.json.txt)

[deployOpenShift.sh.txt](https://github.com/Microsoft/openshift-container-platform/files/1834376/deployOpenShift.sh.txt)
[masterPrep.sh.txt](https://github.com/Microsoft/openshift-container-platform/files/1834378/masterPrep.sh.txt)
[nodePrep.sh.txt](https://github.com/Microsoft/openshift-container-platform/files/1834379/nodePrep.sh.txt)

**Comment by mavis1827** [comment]
@dwaiba i was able to bypass above package version issue and now ran into another issue which is exactly same as https://github.com/Microsoft/openshift-origin/issues/18. Any pointers/suggestions from you would be very helpful. 

Thank you!

**Comment by dwaiba** [comment]
Dear @mavis1827 ... I could provision the clusters both from Portal and azure cli as follows:

`az group create -l westeurope -n openshiftclustering && az group deployment create -g openshiftclustering -n openshiftcluster --template-uri https://raw.githubusercontent.com/dwaiba/openshift-container-platform/master/azuredeploy.json --parameters "{\"openshiftPassword\":{\"value\":\"<<openshift password>>\"},\"enableMetrics\":{\"value\":\"true\"},\"keyVaultResourceGroup\":{\"value\":\"openshiftkvrg\"},\"sshPublicKey\":{\"value\":\"<<ssh key>>\"},\"enableCockpit\":{\"value\":\"true\"},\"rhsmUsernameOrOrgId\":{\"value\":\"<<username>>\"},\"rhsmPasswordOrActivationKey\":{\"value\":\"<<password>>"},\"rhsmPoolId\":{\"value\":\"<<pool ID for OCP 30 day trial>>\"},\"keyVaultName\":{\"value\":\"openshiftprivkeys\"},\"keyVaultSecret\":{\"value\":\"openshiftprivkeys\"},\"aadClientId\":{\"value\":\"<<client ID>>\"},\"aadClientSecret\":{\"value\":\"<<Client secret>>\"}}" --debug`

Obtained the client ID and Client secret as follows [ used both for portal and azure cli]:
`docker run -ti docker4x/create-sp-azure sp-name rg-name rg-region`

Ran Azure cli as follows:
`docker run -dti --name=azure-cli-python --restart=always azuresdk/azure-cli-python && docker exec -ti azure-cli-python bash -c "az login && bash"`

Ofcourse #47 remains but the cluster is well running

**Comment by haroldwongms** [comment]
@dwaiba Why are you installing gluster on the masters?

**Comment by dwaiba** [comment]
Removed glusterd and gluster-blockd for masters as scheduling is disabled

**Pull request closed without merging**
