### PR TITLE
pin docker version to 1.12.6 

### PR DESCRIPTION
**Pull request by miosman**
pin docker version to 1.12.6 to avoid 1.13 being installed due to rhel-7-server-extras-rpms having 1.13 avaible

### CODE REVIEW

**Comment by vincepower** [comment]
@miosman Good catch, but did you find OpenShift actually installed after this change? This does force the correct version of docker, but I still failed validation because the openshift-ansible scripts checked what is available in yum.

**Comment by vincepower** [comment]
Figured out a work around, adding a new pull request that also installs yum-plugin-versionlock and locks the docker file rpm versions.

**Comment by miosman** [comment]
@vincepower to get the installation to complete I used the option to disable the version check. I didn't want to add that in since the openshift-ansible project's PR to fix the issue is to remove the docker version altogether. see https://github.com/openshift/openshift-ansible/pull/7347.  

The current solution from redhat is to disable the version check see https://access.redhat.com/solutions/3376031

**Comment by dwaiba** [comment]
pull #53 with disable version check is a quicker temp fix

**Comment by haroldwongms** [comment]
Since I merged the PR 50, I don't think this one is necessary.  The other PR had a few more items.  Unless someone disagrees, I will be closing this one.

**Pull request closed without merging**
