### PR TITLE
avoid failure for deployment in case system is already registered

### PR DESCRIPTION
**Pull request by Abdelsalam-Abbas**
apply same fixes on master branch from pull request #27

### CODE REVIEW

**Comment by haroldwongms** [comment]
@Abdelsalam-Abbas Can you please make do the same for other branches?

**Comment by haroldwongms** [comment]
@Abdelsalam-Abbas Also, the masterPrep.sh needs to be updated to include this as well.

**Comment by Abdelsalam-Abbas** [comment]
this should include now masterPrep.sh , I am not sure if I should open a new pull request for each branch?

**Comment by Abdelsalam-Abbas** [comment]
@haroldma I have created a pull request for each branch, in case there is a better way to do it let me know to change that. Thanks.

**Comment by haroldwongms** [comment]
@Abdelsalam-Abbas I don't know a better way.  Thanks.

**Pull request merged**
