### PR TITLE
Majorupdate

### PR DESCRIPTION
**Pull request by haroldwongms**
Major update to OCP template for version 3.11.

Many changes to parameters
  - removed some, added some

More hard coded keyvault secrets in use

### CODE REVIEW

**Comment by rasheedamir** [comment]
@haroldwongms when do you think it will be merged? Does the PR work? We need to bootstrap 3.11 cluster so, thinking to use your PR rather than waiting for it to be merged into master

**Comment by haroldwongms** [comment]
@rasheedamir Feel free to try the PR.  I am waiting for the PR to be reviewed before we merge to make sure I didn't miss anything in my testing.

**Comment by haroldwongms** [comment]
Received confirmation from Alessandro that the template is working for him.  Will merge tomorrow if I don't get negative response from @asinn826.

**Comment by asinn826** [comment]
LGTM!

**Pull request merged**
